### ISSUE TITLE
What about virtual comport via USB

### ISSUE THREAD

**Issue by ivand58** [jeelabs/mecrisp-stellaris#1]
Is it possible to interface with the STM32F103C8T6 over USB (VCP) ?

**Comment by jcw** [comment]
Hello - yes, there is a USB driver written in Forth for F103, but it's still buggy. See the [embello](https://github.com/jeelabs/embello/tree/master/explore/1608-forth/suf) repository. I will be posting more about how to set it up and how to work around a problem on the JeeLabs [weblog](http://jeelabs.org) two weeks from now.

**Comment by jcw** [comment]
See http://jeelabs.org/article/1650f/
