### ISSUE TITLE
Infinite loop "unhandled interrupt 00000003"

### ISSUE THREAD

**Issue by jephthai** [jeelabs/mecrisp-stellaris#4]
I have written the Mecrisp bin file to my TI Tiva board with the TM4C1294 chip.  When I connect to the serial terminal, I get an infinite loop of "Unhandled Interrupt 00000003".  I've done a good bit of embedded dev in C, but I'm at a loss how to start figuring out what's wrong here.  

Is the "mecrisp-stellaris-tm4c1294.bin" file created when you build mecrisp known to work for other people on the TI board?  I haven't changed anything at all (it was new in-box this morning!).

**Comment by jcw** [comment]
Just a hunch: I've seen this happen (diff ARM chip) when flash wasn't fully erased before use.

**Comment by jephthai** [comment]
Thanks -- that led me down a path that figured it out.  I had originally tried to burn the image with lm4flash, and it had failed to find the ICD.  So I defaulted back to openocd, and that's what I was using to write the image.  I'm thinking openocd doesn't do it correctly (I noticed that the byte counts weren't right, after staring at the screen long enough!).  I thought I'd try lm4flash again, and it seems after connecting and disconnecting with openocd, lm4flash could now find my ICD.  So it's able to write the BIN file correctly, and now I see this beautiful thing:

    $ sudo ./terminal
    picocom v1.7
    
    port is        : /dev/ttyACM0
    flowcontrol    : none
    baudrate is    : 115200
    parity is      : none
    databits are   : 8
    escape is      : C-a
    local echo is  : no
    noinit is      : no
    noreset is     : no
    nolock is      : no
    send_cmd is    : ascii-xfr -s -l 70 -n
    receive_cmd is : rz -vv
    imap is        : crcrlf,lfcrlf,
    omap is        : crlf,delbs,
    emap is        : crcrlf,delbs,
    
    Terminal ready
    Mecrisp-Stellaris 2.3.6 for TM4C1294 by Matthias Koch
    2 2 + .  4  ok.

So now I know -- "Unhandled Interrupt 00000003" can mean flash is not written correctly. 

Thanks!

**Comment by shorai** [comment]
Thanks,
Works for me as well on  ST Nucleo Board. Had the same problem on STM32F411 Nucleo411RE
Chris :-)

**Comment by olsone** [comment]
I ran into the same issue and cured it by erasing flash. I used only openocd as follows:

Mac OS X 10.11:
```
brew install openocd
openocd -f board/ek-tm4c1294xl.cfg 
```
not necessary: -f interface/ti-icdi.cfg
```
cd mecrisp-stellaris-2.3.9b
telnet localhost 4444
flash erase_address pad 0x000000 0x100000
program stellaris mass_erase 0
./tm4c1294/mecrisp-stellaris-tm4c1294.bin verify reset
```
Yes, that is two methods that say to erase it. I succeeded only after applying both! So maybe there is something wrong with the flash command.

Finally:
```
picocom -b 115200 /dev/cu.usbmodem0F004851 --imap lfcrlf crcrlf --omap delbs crlf
Mecrisp-s 2.3.9 for TM4C1294 by Matthias Koch
```

**Comment by jcw** [comment]
> flash erase_address pad 0x000000 0x100000

Maybe this works better, as sole command?

    flash erase_address pad 0x8000000 0x8100000

(flash is indeed normally mapped to zero, but its native address is 0x08000000-up on STM32)

**Comment by lmamakos** [comment]
I had an issue with Maple Mini clones (STM32F103CBT6, I think) which has part of the flash protected.  I think it contained the Arduino bootloader?  I managed to fine a version stm32loader.py that could remove the write-protect from that sector of the flash and then erase it.  I don't for for sure if this is the cause of your issue..

**Comment by shorai** [comment]
Hi and many thanks, erasing the chip first clears the problem

Thanks again for an amazing FORTH which I am growing to love after a long
hiatus.

Chris
